# Changes here will be overwritten by Copier
_commit: 0.0.6
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
python_main_version: '3.10'
repository_name: tap-pipedream
repository_namespace: edgarrmondragon
repository_provider: github.com
tap_auth_method: Bearer Token
tap_id: tap-pipedream
tap_package_command_line_name: tap-pipedream
tap_package_distribution_name: tap-pipedream
tap_package_import_name: tap_pipedream
tap_source_description: Pipedream is an integration platform for developers.
tap_source_id: Pipedream
tap_source_name: Pipedream
tap_stream_type: REST
vscode_files: true
